[workspace]
members = [
    "crates/app", "crates/asset", "crates/corelib",
    "crates/platform", "crates/renderer",
]
resolver = "2"

[workspace.package]
version = "0.1.8"
edition = "2024"
license = "MIT"

[workspace.dependencies]
log = "0.4.28"
anyhow = "1.0.99"
env_logger = "0.11.8"
