[package]
name = "platform"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
log.workspace = true
anyhow.workspace = true
winit = "0.30.12"
pollster = "0.4.0"
renderer = { path = "../renderer" }
wgpu = "26.0.1"
