[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
platform = { path = "../platform" }
wgpu = "26.0.1"
