[package]
name = "asset"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
log.workspace = true
image = { version = "0.25.5", default-features = false, features = ["png"] }
